spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  application:
    name: calendar-service
  datasource:
    url: jdbc:mysql://localhost:3306/calendar?useUnicode=true&serverTimezone=Asia/Seoul
    hikari:
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: qwe1212
  jpa:
    database: mysql
    show-sql: true
    properties:
      hibernate:
        show_sql: true # SQL 출력
        format_sql: true # 포매터 적용
        use_sql_comments: true # JPQL 출력
        ddl-auto: update

decorator:
  datasource:
    p6spy:
      enable-logging: true

logging.level:
  org.hibernate.type: trace # 쿼리 파라미터 출력


server:
  tomcat:
    max-http-form-post-size: 10MB

secret-key: calendar-service-java-web-token-secretKey-is-aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
